### ISSUE TITLE
Add RSS/Atom support

### ISSUE THREAD

**Issue by meeDamian** [meeDamian/meeDamian.github.io#15]

**Comment by meeDamian** [comment]
@amulware I don't use feeds so please confirm it works :)

**Comment by paulcscharf** [comment]
I use Feedly, which has trouble adding https://meedamian.com/, but if I try https://meedamian.com/feed/ instead, it works fine. A bit odd, but at least this works for me with a bit of a work around there. ¯_(ツ)_/¯

**Comment by meeDamian** [comment]
FFFUUUUUU, I guess it just can't be that simple… I'll look into it.

**Comment by meeDamian** [comment]
Fixed it for feedly (:

**Comment by paulcscharf** [comment]
Can confirm. Working great. :D
